# Configuration for the FitLayout backend server.
# See https://github.com/FitLayout/FitLayoutWeb for details on how to run the server.
# Configuration properties for a "localdir" repositories. Normally, just setting
# filayout.rdf.path to point to the folder when the repositores live is sufficient.
# Each subfolder in the configured folder is used as a repository.
# It's better to shutdown the server before adding/removing repositories.
fitlayout.rdf.storage=localdir
fitlayout.rdf.maxQueryLimit=500000
# Edit this to point to your repository location
fitlayout.rdf.path=/opt/storage/localdir
